# Generated by Django 2.1 on 2019-11-24 09:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190915_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article/%Y%m%d/', verbose_name='标题图'),
        ),
    ]
